spring:
  datasource:
    url: jdbc:sqlite:D:/IdeaProjects/2023-SE-HomeWork/se-web/src/main/resources/db/data.db
    driver-class-name: org.sqlite.JDBC
  web:
    resources:
      static-locations: ${static_locations}
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    whitelabel:
      enabled: false
#  port: 443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 1145141919810
#    key-store-type: PKCS12
#    key-alias: tomcat

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    io.github.nickid2018.ipgs.dao: debug

security:
  basic:
    enabled: false

